# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MHW' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MHW
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  
  target 'MHW-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MHWTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'MHW-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!
#
#   # Pods for MHW-tvOS
#
#   target 'MHW-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end
